# Generated by Django 3.2 on 2022-02-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdislike',
            name='created',
        ),
        migrations.RemoveField(
            model_name='commentdislike',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='created',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='created',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='created',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='updated',
        ),
    ]
