# Generated by Django 3.2 on 2022-02-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibition', '0003_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='report',
        ),
        migrations.AddField(
            model_name='post',
            name='art_form',
            field=models.IntegerField(choices=[(0, 'Painting'), (1, 'Photography'), (2, 'Music'), (3, 'Graphic Design'), (4, 'Fashion'), (5, 'Sculpture'), (6, 'Architecture'), (7, 'Fine Art')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='report_post',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
