# Generated by Django 3.2 on 2022-02-21 01:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_auto_20220220_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='report_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Media'),
        ),
    ]
