# Generated by Django 3.2 on 2022-02-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_auto_20220221_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
