# Generated by Django 3.2 on 2022-02-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_remove_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='art_form',
            new_name='artform',
        ),
    ]
