# Generated by Django 3.2 on 2022-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0007_rename_art_form_post_artform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artform',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Photography', 'Photography'), ('Music', 'Music'), ('Graphic Design', 'Graphic Design'), ('Fashion', 'Fashion'), ('Sculpture', 'Sculpture'), ('Architecture', 'Architecture'), ('Fine Art', 'Fine Art')], default='Painting', max_length=20),
        ),
    ]
