# Generated by Django 3.2 on 2022-03-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_alter_post_artform'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
