# Generated by Django 3.2 on 2022-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0010_rename_status_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artform',
            field=models.CharField(choices=[('painting', 'Painting'), ('photography', 'Photography'), ('music', 'Music'), ('graphic-design', 'Graphic Design'), ('fashion', 'Fashion'), ('sculpture', 'Sculpture'), ('architecture', 'Architecture'), ('fine-art', 'Fine Art')], default='Painting', max_length=20),
        ),
    ]
