# Generated by Django 3.2 on 2022-03-17 21:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0012_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video'),
        ),
    ]
