# Generated by Django 3.2 on 2022-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0013_auto_20220317_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AlterField(
            model_name='post',
            name='artform',
            field=models.CharField(choices=[('painting', 'Painting'), ('sketching', 'Sketching'), ('photography', 'Photography'), ('graphic-design', 'Graphic Design'), ('fashion', 'Fashion'), ('sculpture', 'Sculpture'), ('architecture', 'Architecture'), ('fine-art', 'Fine Art')], default='Painting', max_length=20),
        ),
    ]
