# Generated by Django 3.2 on 2022-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0014_auto_20220318_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=200, null=True),
        ),
    ]
