# Generated by Django 3.2 on 2022-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0016_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
