# Generated by Django 3.2 on 2022-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0017_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artform',
            field=models.CharField(choices=[('Painting', 'painting'), ('Photography', 'photography'), ('Sketching', 'sketching'), ('Graphic Design', 'graphic-design'), ('Fashion', 'fashion'), ('Sculpture', 'sculpture'), ('Architecture', 'architecture'), ('Fine Art', 'fine-art')], default='Painting', max_length=20),
        ),
    ]
