# Generated by Django 3.2 on 2022-02-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='report_comment',
        ),
    ]
