# Generated by Django 3.2 on 2022-02-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreport',
            old_name='reported_user',
            new_name='reporting_user',
        ),
        migrations.RenameField(
            model_name='postreport',
            old_name='reported_user',
            new_name='reporting_user',
        ),
    ]
