# Generated by Django 3.2 on 2022-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20220221_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='updated',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='more_info',
            field=models.TextField(default=False, max_length=300),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Explicit Content'), (1, 'Inappropriate Image'), (2, 'Profanity'), (3, 'Offensive'), (4, 'Violence'), (5, 'Bullying'), (6, 'Harassment')], default=0),
        ),
        migrations.AddField(
            model_name='postreport',
            name='more_info',
            field=models.TextField(default=False, max_length=300),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Explicit Content'), (1, 'Inappropriate Image'), (2, 'Profanity'), (3, 'Offensive'), (4, 'Violence'), (5, 'Bullying'), (6, 'Harassment')], default=0),
        ),
    ]
