# Generated by Django 3.2 on 2022-02-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220221_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='more_info',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='more_info',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
