# Generated by Django 3.2 on 2022-03-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20220221_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='reported_post',
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='reporting_user',
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
        migrations.DeleteModel(
            name='PostReport',
        ),
    ]
